db:
  username: ${username.value:postgres}
  password: PROPER4321Qw
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/company_repository
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  file:
    name: spring.log
    path: /
  level:
    root: INFO
    com.dmdev.spring.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/company_repository
    username: postgres
    password: PROPER4321Qw
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: spring
    open-in-view: false
